### ISSUE TITLE
`null` Certificate

### ISSUE THREAD

**Issue by JesusMcCloud** [a-sit-plus/vck#106]
I know what the API docs say and using raw public keys is a legit use case.
HOWEVER, it seems funky [here](https://github.com/a-sit-plus/vck/blob/db5856f84fbcf53b274de5aae12292b05a478c6a/vck-openid/src/commonMain/kotlin/at/asitplus/wallet/lib/oidvci/WalletService.kt#L507) to let this just pass

**Comment by nodh** [comment]
Code is obsolete after merging https://github.com/a-sit-plus/vck/pull/130
