### ISSUE TITLE
Initializer is not Thread-Safe

### ISSUE THREAD

**Issue by JesusMcCloud** [a-sit-plus/vck#13]
Registering polymorphic serializers for credential types sometimes happens twice. Adding spring-boot-devtools to a service's classpath triggers this, if the Initializer is called upon startup

**Comment by nodh** [comment]
Is this still an issue?

**Comment by JesusMcCloud** [comment]
i don't know. adding it to my backlog

**Comment by JesusMcCloud** [comment]
we can reopen, if it happens again
